// generated by contentful-to-sanity
import { defineField, defineType, type SchemaTypeDefinition } from "sanity";

const validateIn = (values: (string | number)[], value: any) =>
  values.includes(value) ? true : `Value must be one of ${values.join(", ")}`;

export const projectType = defineType({
  type: "document",
  name: "project",
  title: "Project",
  description: "art projects",
  fields: [
    defineField({
      name: "title",
      type: "string",
      title: "Title",
      hidden: false,
    }),
    defineField({
      name: "medium",
      type: "string",
      title: "Medium",
      hidden: false,
    }),
    defineField({
      name: "materials",
      type: "string",
      title: "Materials",
      hidden: false,
    }),
    defineField({
      name: "date",
      type: "datetime",
      title: "Date",
      hidden: false,
      options: { timeFormat: "H:mmZ" },
    }),
    defineField({ name: "year", type: "string", title: "Year", hidden: false }),
    defineField({
      name: "type",
      type: "string",
      title: "Type",
      hidden: false,
      validation: (Rule) =>
        Rule.required().custom((value) =>
          validateIn(["Installation", "Writing"], value),
        ),
      options: { list: ["Installation", "Writing"] },
    }),
    defineField({
      name: "featured",
      type: "boolean",
      title: "Featured",
      hidden: false,
    }),
    defineField({
      name: "content",
      type: "array",
      of: [
        {
          type: "block",
          styles: [
            { title: "Heading 2", value: "h2" },
            { title: "Quote", value: "blockquote" },
          ],
          lists: [
            { title: "Bullet", value: "bullet" },
            { title: "Numbered", value: "number" },
          ],
          marks: {
            decorators: [
              { title: "Strong", value: "strong" },
              { title: "Emphasis", value: "em" },
              { title: "Code", value: "code" },
              { title: "Underline", value: "underline" },
            ],
            annotations: [
              {
                type: "object",
                name: "link",
                title: "url",
                fields: [
                  defineField({
                    type: "string",
                    name: "href",
                    title: "URL",
                    validation: (Rule) => Rule.required(),
                  }),
                  defineField({
                    type: "string",
                    name: "target",
                    title: "Target",
                    options: {
                      list: [
                        { value: "_blank", title: "Blank" },
                        { value: "_parent", title: "Parent" },
                      ],
                    },
                  }),
                ],
              },
              {
                type: "reference",
                name: "reference",
                title: "Reference",
                to: [
                  { type: "project" },
                  { type: "heroImages" },
                  { type: "about" },
                  { type: "imageWithFocalPoint" },
                  { type: "assets" },
                  { type: "documentation" },
                  { type: "imageWide" },
                  { type: "containerVideo" },
                  { type: "carousel" },
                  { type: "blogPost" },
                  { type: "baseContent" },
                  { type: "textSection" },
                  { type: "contentSecion" },
                  { type: "metadataSection" },
                ],
              },
              { type: "image" },
              { type: "file" },
            ],
          },
          of: [
            {
              type: "reference",
              title: "Reference",
              to: [
                { type: "project" },
                { type: "heroImages" },
                { type: "about" },
                { type: "imageWithFocalPoint" },
                { type: "assets" },
                { type: "documentation" },
                { type: "imageWide" },
                { type: "containerVideo" },
                { type: "carousel" },
                { type: "blogPost" },
                { type: "baseContent" },
                { type: "textSection" },
                { type: "contentSecion" },
                { type: "metadataSection" },
              ],
            },
          ],
        },
        {
          type: "reference",
          title: "Reference",
          to: [
            { type: "project" },
            { type: "heroImages" },
            { type: "about" },
            { type: "imageWithFocalPoint" },
            { type: "assets" },
            { type: "documentation" },
            { type: "imageWide" },
            { type: "containerVideo" },
            { type: "carousel" },
            { type: "blogPost" },
            { type: "baseContent" },
            { type: "textSection" },
            { type: "contentSecion" },
            { type: "metadataSection" },
          ],
        },
        { type: "image" },
        { type: "file" },
        { type: "break" },
      ],
      title: "Content",
      hidden: false,
    }),
    defineField({
      name: "documentation",
      type: "array",
      of: [{ type: "image", options: { hotspot: true } }],
      title: "Documentation",
      hidden: false,
    }),
    defineField({
      name: "url",
      type: "string",
      title: "url",
      hidden: false,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "featuredImage",
      type: "image",
      title: "Featured Image",
      hidden: false,
      options: { hotspot: true },
      validation: (Rule) => Rule.required(),
    }),
    defineField({ name: "video", type: "file", title: "Video", hidden: false }),
    defineField({
      name: "sections",
      type: "array",
      of: [
        {
          type: "reference",
          to: [
            { type: "project" },
            { type: "heroImages" },
            { type: "about" },
            { type: "imageWithFocalPoint" },
            { type: "assets" },
            { type: "documentation" },
            { type: "imageWide" },
            { type: "containerVideo" },
            { type: "carousel" },
            { type: "blogPost" },
            { type: "baseContent" },
            { type: "textSection" },
            { type: "contentSecion" },
            { type: "metadataSection" },
          ],
        },
      ],
      title: "Sections",
      hidden: false,
      options: { layout: "grid" },
    }),
    defineField({
      name: "metadataSections",
      type: "array",
      of: [{ type: "reference", to: [{ type: "metadataSection" }] }],
      title: "Metadata Sections",
      hidden: false,
    }),
    defineField({
      type: "boolean",
      description:
        "If this document was archived on Contentful at the time of export, the document will be in a read-only state.",
      name: "contentfulArchived",
      readOnly: true,
    }),
  ],
  preview: { select: { title: "title" } },
  readOnly: ({ document }) =>
    (document == null ? void 0 : document.contentfulArchived) === !0,
});

export const heroImagesType = defineType({
  type: "document",
  name: "heroImages",
  title: "Hero images",
  description: "A group of images to be displayed on the index page",
  fields: [
    defineField({
      name: "title",
      type: "string",
      title: "Title",
      hidden: false,
    }),
    defineField({
      name: "description",
      type: "string",
      title: "Description",
      hidden: false,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "image",
      type: "image",
      title: "Image",
      hidden: false,
      options: { hotspot: true },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "slug",
      type: "string",
      title: "Slug",
      hidden: false,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "imageFp",
      type: "reference",
      title: "ImageFP",
      hidden: false,
      to: [{ type: "imageWithFocalPoint" }],
    }),
    defineField({
      type: "boolean",
      description:
        "If this document was archived on Contentful at the time of export, the document will be in a read-only state.",
      name: "contentfulArchived",
      readOnly: true,
    }),
  ],
  preview: { select: { title: "description" } },
  readOnly: ({ document }) =>
    (document == null ? void 0 : document.contentfulArchived) === !0,
});

export const aboutType = defineType({
  type: "document",
  name: "about",
  title: "Page",
  description: "A generic page model (like for an about page)",
  fields: [
    defineField({
      name: "title",
      type: "string",
      title: "Title",
      hidden: false,
    }),
    defineField({ name: "image", type: "image", title: "Image", hidden: false, options: { hotspot: true } }),
    defineField({
      name: "description",
      type: "array",
      of: [{ type: "block" }, { type: "image" }],
      title: "Description",
      hidden: false,
    }),
    defineField({ name: "slug", type: "string", title: "slug", hidden: false }),
    defineField({
      name: "richDescription",
      type: "array",
      of: [
        {
          type: "block",
          styles: [
            { title: "Heading 1", value: "h1" },
            { title: "Heading 2", value: "h2" },
            { title: "Heading 3", value: "h3" },
            { title: "Heading 4", value: "h4" },
            { title: "Heading 5", value: "h5" },
            { title: "Heading 6", value: "h6" },
            { title: "Quote", value: "blockquote" },
          ],
          lists: [
            { title: "Bullet", value: "bullet" },
            { title: "Numbered", value: "number" },
          ],
          marks: {
            decorators: [
              { title: "Strong", value: "strong" },
              { title: "Emphasis", value: "em" },
              { title: "Code", value: "code" },
              { title: "Underline", value: "underline" },
            ],
            annotations: [
              {
                type: "object",
                name: "link",
                title: "url",
                fields: [
                  defineField({
                    type: "string",
                    name: "href",
                    title: "URL",
                    validation: (Rule) => Rule.required(),
                  }),
                  defineField({
                    type: "string",
                    name: "target",
                    title: "Target",
                    options: {
                      list: [
                        { value: "_blank", title: "Blank" },
                        { value: "_parent", title: "Parent" },
                      ],
                    },
                  }),
                ],
              },
              {
                type: "reference",
                name: "reference",
                title: "Reference",
                to: [
                  { type: "project" },
                  { type: "heroImages" },
                  { type: "about" },
                  { type: "imageWithFocalPoint" },
                  { type: "assets" },
                  { type: "documentation" },
                  { type: "imageWide" },
                  { type: "containerVideo" },
                  { type: "carousel" },
                  { type: "blogPost" },
                  { type: "baseContent" },
                  { type: "textSection" },
                  { type: "contentSecion" },
                  { type: "metadataSection" },
                ],
              },
              { type: "image" },
              { type: "file" },
            ],
          },
          of: [
            {
              type: "reference",
              title: "Reference",
              to: [
                { type: "project" },
                { type: "heroImages" },
                { type: "about" },
                { type: "imageWithFocalPoint" },
                { type: "assets" },
                { type: "documentation" },
                { type: "imageWide" },
                { type: "containerVideo" },
                { type: "carousel" },
                { type: "blogPost" },
                { type: "baseContent" },
                { type: "textSection" },
                { type: "contentSecion" },
                { type: "metadataSection" },
              ],
            },
          ],
        },
        {
          type: "reference",
          title: "Reference",
          to: [
            { type: "project" },
            { type: "heroImages" },
            { type: "about" },
            { type: "imageWithFocalPoint" },
            { type: "assets" },
            { type: "documentation" },
            { type: "imageWide" },
            { type: "containerVideo" },
            { type: "carousel" },
            { type: "blogPost" },
            { type: "baseContent" },
            { type: "textSection" },
            { type: "contentSecion" },
            { type: "metadataSection" },
          ],
        },
        { type: "image" },
        { type: "file" },
        { type: "break" },
      ],
      title: "richDescription",
      hidden: false,
    }),
    defineField({
      type: "boolean",
      description:
        "If this document was archived on Contentful at the time of export, the document will be in a read-only state.",
      name: "contentfulArchived",
      readOnly: true,
    }),
  ],
  preview: { select: { title: "title" } },
  readOnly: ({ document }) =>
    (document == null ? void 0 : document.contentfulArchived) === !0,
});

export const imageWithFocalPointType = defineType({
  type: "document",
  name: "imageWithFocalPoint",
  title: "Image with Focal Point",
  description: null,
  fields: [
    defineField({
      name: "title",
      type: "string",
      title: "Title",
      hidden: false,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "image",
      type: "image",
      title: "Image",
      hidden: false,
      options: { hotspot: true },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      type: "boolean",
      description:
        "If this document was archived on Contentful at the time of export, the document will be in a read-only state.",
      name: "contentfulArchived",
      readOnly: true,
    }),
  ],
  preview: { select: { title: "title" } },
  readOnly: ({ document }) =>
    (document == null ? void 0 : document.contentfulArchived) === !0,
});

export const assetsType = defineType({
  type: "document",
  name: "assets",
  title: "Assets",
  description:
    "Common assets on the website such as logos, images and favicons",
  fields: [
    defineField({ name: "asset", type: "image", title: "asset", hidden: false, options: { hotspot: true } }),
    defineField({
      type: "boolean",
      description:
        "If this document was archived on Contentful at the time of export, the document will be in a read-only state.",
      name: "contentfulArchived",
      readOnly: true,
    }),
  ],
  readOnly: ({ document }) =>
    (document == null ? void 0 : document.contentfulArchived) === !0,
});

export const documentationType = defineType({
  type: "document",
  name: "documentation",
  title: "documentation",
  description: "A collection of multiple images",
  fields: [
    defineField({
      name: "title",
      type: "string",
      title: "Title",
      hidden: false,
    }),
    defineField({
      name: "images",
      type: "array",
      of: [{ type: "image", options: { hotspot: true } }],
      title: "images",
      hidden: false,
    }),
    defineField({
      name: "description",
      type: "string",
      title: "Description",
      hidden: false,
    }),
    defineField({
      type: "boolean",
      description:
        "If this document was archived on Contentful at the time of export, the document will be in a read-only state.",
      name: "contentfulArchived",
      readOnly: true,
    }),
  ],
  preview: { select: { title: "title" } },
  readOnly: ({ document }) =>
    (document == null ? void 0 : document.contentfulArchived) === !0,
});

export const imageWideType = defineType({
  type: "document",
  name: "imageWide",
  title: "Section - Image Wide",
  description:
    "A full width image, for instance for landscape photos, or a hero image",
  fields: [
    defineField({
      name: "title",
      type: "string",
      title: "Title",
      hidden: false,
    }),
    defineField({ name: "alt", type: "string", title: "Alt", hidden: false }),
    defineField({ name: "image", type: "image", title: "Image", hidden: false, options: { hotspot: true } }),
    defineField({
      type: "boolean",
      description:
        "If this document was archived on Contentful at the time of export, the document will be in a read-only state.",
      name: "contentfulArchived",
      readOnly: true,
    }),
  ],
  preview: { select: { title: "title" } },
  readOnly: ({ document }) =>
    (document == null ? void 0 : document.contentfulArchived) === !0,
});

export const containerVideoType = defineType({
  type: "document",
  name: "containerVideo",
  title: "ContainerVideo",
  description: "A video block inside a container with a maximum width",
  fields: [
    defineField({
      name: "title",
      type: "string",
      title: "Title",
      hidden: false,
    }),
    defineField({ name: "video", type: "file", title: "video", hidden: false }),
    defineField({ name: "image", type: "image", title: "Image", hidden: false, options: { hotspot: true } }),
    defineField({
      type: "boolean",
      description:
        "If this document was archived on Contentful at the time of export, the document will be in a read-only state.",
      name: "contentfulArchived",
      readOnly: true,
    }),
  ],
  preview: { select: { title: "title" } },
  readOnly: ({ document }) =>
    (document == null ? void 0 : document.contentfulArchived) === !0,
});

export const carouselType = defineType({
  type: "document",
  name: "carousel",
  title: "Carousel",
  description:
    "Renders a carousel with different options (delay, controls, title, captions)",
  fields: [
    defineField({
      name: "title",
      type: "string",
      title: "Title",
      hidden: false,
    }),
    defineField({
      name: "images",
      type: "array",
      of: [{ type: "image", options: { hotspot: true } }],
      title: "Images",
      hidden: false,
    }),
    defineField({
      name: "pause",
      type: "boolean",
      title: "pause",
      hidden: false,
      description: "Should the carousel be able to pause?",
    }),
    defineField({
      name: "indicators",
      type: "boolean",
      title: "indicators",
      hidden: false,
      description: "Should the carousel have indicators?",
    }),
    defineField({
      name: "controls",
      type: "boolean",
      title: "controls",
      hidden: false,
      description: "Should the carousel have controls?",
    }),
    defineField({
      name: "interval",
      type: "number",
      title: "interval",
      hidden: false,
      description:
        "The amount of time to delay between automatically cycling an item. If false, carousel will not automatically cycle.",
      validation: (Rule) => Rule.integer(),
    }),
    defineField({
      type: "boolean",
      description:
        "If this document was archived on Contentful at the time of export, the document will be in a read-only state.",
      name: "contentfulArchived",
      readOnly: true,
    }),
  ],
  preview: { select: { title: "title" } },
  readOnly: ({ document }) =>
    (document == null ? void 0 : document.contentfulArchived) === !0,
});

export const blogPostType = defineType({
  type: "document",
  name: "blogPost",
  title: "Blog Post",
  description: "The model for our blog posts",
  fields: [
    defineField({
      name: "title",
      type: "string",
      title: "title",
      hidden: false,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "subtitle",
      type: "string",
      title: "subtitle",
      hidden: false,
    }),
    defineField({ name: "url", type: "string", title: "url", hidden: false }),
    defineField({
      name: "publishDate",
      type: "datetime",
      title: "publishDate",
      hidden: false,
      validation: (Rule) => Rule.required(),
      options: { timeFormat: "H:mmZ" },
    }),
    defineField({
      name: "featuredImage",
      type: "image",
      title: "featuredImage",
      hidden: false,
      options: { hotspot: true },
    }),
    defineField({
      name: "content",
      type: "array",
      of: [
        {
          type: "block",
          styles: [
            { title: "Heading 1", value: "h1" },
            { title: "Heading 2", value: "h2" },
            { title: "Heading 3", value: "h3" },
            { title: "Heading 4", value: "h4" },
            { title: "Heading 5", value: "h5" },
            { title: "Heading 6", value: "h6" },
            { title: "Quote", value: "blockquote" },
          ],
          lists: [
            { title: "Bullet", value: "bullet" },
            { title: "Numbered", value: "number" },
          ],
          marks: {
            decorators: [
              { title: "Strong", value: "strong" },
              { title: "Emphasis", value: "em" },
              { title: "Code", value: "code" },
              { title: "Underline", value: "underline" },
            ],
            annotations: [
              {
                type: "object",
                name: "link",
                title: "url",
                fields: [
                  defineField({
                    type: "string",
                    name: "href",
                    title: "URL",
                    validation: (Rule) => Rule.required(),
                  }),
                  defineField({
                    type: "string",
                    name: "target",
                    title: "Target",
                    options: {
                      list: [
                        { value: "_blank", title: "Blank" },
                        { value: "_parent", title: "Parent" },
                      ],
                    },
                  }),
                ],
              },
              {
                type: "reference",
                name: "reference",
                title: "Reference",
                to: [
                  { type: "project" },
                  { type: "heroImages" },
                  { type: "about" },
                  { type: "imageWithFocalPoint" },
                  { type: "assets" },
                  { type: "documentation" },
                  { type: "imageWide" },
                  { type: "containerVideo" },
                  { type: "carousel" },
                  { type: "blogPost" },
                  { type: "baseContent" },
                  { type: "textSection" },
                  { type: "contentSecion" },
                  { type: "metadataSection" },
                ],
              },
              { type: "image" },
              { type: "file" },
            ],
          },
          of: [
            {
              type: "reference",
              title: "Reference",
              to: [
                { type: "project" },
                { type: "heroImages" },
                { type: "about" },
                { type: "imageWithFocalPoint" },
                { type: "assets" },
                { type: "documentation" },
                { type: "imageWide" },
                { type: "containerVideo" },
                { type: "carousel" },
                { type: "blogPost" },
                { type: "baseContent" },
                { type: "textSection" },
                { type: "contentSecion" },
                { type: "metadataSection" },
              ],
            },
          ],
        },
        {
          type: "reference",
          title: "Reference",
          to: [
            { type: "project" },
            { type: "heroImages" },
            { type: "about" },
            { type: "imageWithFocalPoint" },
            { type: "assets" },
            { type: "documentation" },
            { type: "imageWide" },
            { type: "containerVideo" },
            { type: "carousel" },
            { type: "blogPost" },
            { type: "baseContent" },
            { type: "textSection" },
            { type: "contentSecion" },
            { type: "metadataSection" },
          ],
        },
        { type: "image" },
        { type: "file" },
        { type: "break" },
      ],
      title: "content",
      hidden: false,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      type: "boolean",
      description:
        "If this document was archived on Contentful at the time of export, the document will be in a read-only state.",
      name: "contentfulArchived",
      readOnly: true,
    }),
  ],
  preview: { select: { title: "title" } },
  readOnly: ({ document }) =>
    (document == null ? void 0 : document.contentfulArchived) === !0,
});

export const baseContentType = defineType({
  type: "document",
  name: "baseContent",
  title: "Base Content",
  description:
    "a base content type that both projects and blog posts will inherit from",
  fields: [
    defineField({
      name: "title",
      type: "string",
      title: "title",
      hidden: false,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "featuredImage",
      type: "image",
      title: "featuredImage",
      hidden: false,
      options: { hotspot: true },
    }),
    defineField({
      name: "references",
      type: "array",
      of: [{ type: "reference", to: [{ type: "contentSecion" }] }],
      title: "references",
      hidden: false,
      options: { layout: "grid" },
    }),
    defineField({
      name: "slug",
      type: "string",
      title: "slug",
      hidden: false,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "sections",
      type: "array",
      of: [{ type: "reference", to: [{ type: "contentSecion" }] }],
      title: "sections",
      hidden: false,
    }),
    defineField({
      type: "boolean",
      description:
        "If this document was archived on Contentful at the time of export, the document will be in a read-only state.",
      name: "contentfulArchived",
      readOnly: true,
    }),
  ],
  preview: { select: { title: "title" } },
  readOnly: ({ document }) =>
    (document == null ? void 0 : document.contentfulArchived) === !0,
});

export const textSectionType = defineType({
  type: "document",
  name: "textSection",
  title: "Text Section",
  description: "section text type for projects and blog posts",
  fields: [
    defineField({
      name: "layout",
      type: "string",
      title: "layout",
      hidden: false,
      description:
        "Full: spans entire width, Two-column: splits into equal halves, Three-column: splits into thirds, Split: customizable column ratio",
      initialValue: "full",
      validation: (Rule) =>
        Rule.custom((value) =>
          validateIn(["full", "two-column", "three-column", "split"], value),
        ),
      options: {
        list: ["full", "two-column", "three-column", "split"],
        layout: "dropdown",
      },
    }),
    defineField({
      name: "width",
      type: "string",
      title: "width",
      hidden: false,
      description: "Choose the width of this section",
      initialValue: "full",
      validation: (Rule) =>
        Rule.custom((value) =>
          validateIn(["narrow", "medium", "wide", "full"], value),
        ),
      options: {
        list: ["narrow", "medium", "wide", "full"],
        layout: "dropdown",
      },
    }),
    defineField({
      name: "alignment",
      type: "string",
      title: "alignment",
      hidden: false,
      description: "Text alignment",
      initialValue: "center",
      validation: (Rule) =>
        Rule.custom((value) => validateIn(["center", "left", "right"], value)),
      options: { list: ["center", "left", "right"], layout: "radio" },
    }),
    defineField({
      name: "columnSpan",
      type: "number",
      title: "columnSpan",
      hidden: false,
      description: "How many columns this section should span (1-3)",
      initialValue: 1,
      validation: (Rule) =>
        Rule.integer().custom((value) => validateIn([1, 2, 3], value)),
      options: { list: [1, 2, 3], layout: "dropdown" },
    }),
    defineField({
      name: "content",
      type: "array",
      of: [
        {
          type: "block",
          styles: [
            { title: "Heading 1", value: "h1" },
            { title: "Heading 2", value: "h2" },
            { title: "Heading 3", value: "h3" },
            { title: "Heading 4", value: "h4" },
            { title: "Heading 5", value: "h5" },
            { title: "Heading 6", value: "h6" },
            { title: "Quote", value: "blockquote" },
          ],
          lists: [
            { title: "Bullet", value: "bullet" },
            { title: "Numbered", value: "number" },
          ],
          marks: {
            decorators: [
              { title: "Strong", value: "strong" },
              { title: "Emphasis", value: "em" },
              { title: "Code", value: "code" },
              { title: "Underline", value: "underline" },
            ],
            annotations: [
              {
                type: "object",
                name: "link",
                title: "url",
                fields: [
                  defineField({
                    type: "string",
                    name: "href",
                    title: "URL",
                    validation: (Rule) => Rule.required(),
                  }),
                  defineField({
                    type: "string",
                    name: "target",
                    title: "Target",
                    options: {
                      list: [
                        { value: "_blank", title: "Blank" },
                        { value: "_parent", title: "Parent" },
                      ],
                    },
                  }),
                ],
              },
              {
                type: "reference",
                name: "reference",
                title: "Reference",
                to: [
                  { type: "project" },
                  { type: "heroImages" },
                  { type: "about" },
                  { type: "imageWithFocalPoint" },
                  { type: "assets" },
                  { type: "documentation" },
                  { type: "imageWide" },
                  { type: "containerVideo" },
                  { type: "carousel" },
                  { type: "blogPost" },
                  { type: "baseContent" },
                  { type: "textSection" },
                  { type: "contentSecion" },
                  { type: "metadataSection" },
                ],
              },
              { type: "image" },
              { type: "file" },
            ],
          },
          of: [
            {
              type: "reference",
              title: "Reference",
              to: [
                { type: "project" },
                { type: "heroImages" },
                { type: "about" },
                { type: "imageWithFocalPoint" },
                { type: "assets" },
                { type: "documentation" },
                { type: "imageWide" },
                { type: "containerVideo" },
                { type: "carousel" },
                { type: "blogPost" },
                { type: "baseContent" },
                { type: "textSection" },
                { type: "contentSecion" },
                { type: "metadataSection" },
              ],
            },
          ],
        },
        {
          type: "reference",
          title: "Reference",
          to: [
            { type: "project" },
            { type: "heroImages" },
            { type: "about" },
            { type: "imageWithFocalPoint" },
            { type: "assets" },
            { type: "documentation" },
            { type: "imageWide" },
            { type: "containerVideo" },
            { type: "carousel" },
            { type: "blogPost" },
            { type: "baseContent" },
            { type: "textSection" },
            { type: "contentSecion" },
            { type: "metadataSection" },
          ],
        },
        { type: "image" },
        { type: "file" },
        { type: "break" },
      ],
      title: "content",
      hidden: false,
    }),
    defineField({
      type: "boolean",
      description:
        "If this document was archived on Contentful at the time of export, the document will be in a read-only state.",
      name: "contentfulArchived",
      readOnly: true,
    }),
  ],
  preview: { select: { title: "layout" } },
  readOnly: ({ document }) =>
    (document == null ? void 0 : document.contentfulArchived) === !0,
});

export const contentSecionType = defineType({
  type: "document",
  name: "contentSecion",
  title: "ContentSecion",
  description: "",
  fields: [
    defineField({
      name: "type",
      type: "string",
      title: "type",
      hidden: false,
      initialValue: "text",
      validation: (Rule) =>
        Rule.custom((value) =>
          validateIn(
            ["text", "image", "video", "gallery", "quote", "embed"],
            value,
          ),
        ),
      options: {
        list: ["text", "image", "video", "gallery", "quote", "embed"],
        layout: "dropdown",
      },
    }),
    defineField({
      name: "layout",
      type: "string",
      title: "layout",
      hidden: false,
      initialValue: "full",
      validation: (Rule) =>
        Rule.custom((value) =>
          validateIn(["full", "two-column", "three-column", "grid"], value),
        ),
      options: {
        list: ["full", "two-column", "three-column", "grid"],
        layout: "dropdown",
      },
    }),
    defineField({
      name: "order",
      type: "number",
      title: "order",
      hidden: false,
      initialValue: 1,
      validation: (Rule) => Rule.integer(),
    }),
    defineField({
      type: "boolean",
      description:
        "If this document was archived on Contentful at the time of export, the document will be in a read-only state.",
      name: "contentfulArchived",
      readOnly: true,
    }),
  ],
  preview: { select: { title: "type" } },
  readOnly: ({ document }) =>
    (document == null ? void 0 : document.contentfulArchived) === !0,
});

export const metadataSectionType = defineType({
  type: "document",
  name: "metadataSection",
  title: "Metadata Section",
  description:
    "Flexible metadata sections for projects with configurable titles and rich text content",
  fields: [
    defineField({
      name: "title",
      type: "string",
      title: "Title",
      hidden: false,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "content",
      type: "array",
      of: [
        {
          type: "block",
          styles: [
            { title: "Heading 2", value: "h2" },
            { title: "Heading 3", value: "h3" },
            { title: "Heading 4", value: "h4" },
          ],
          lists: [
            { title: "Bullet", value: "bullet" },
            { title: "Numbered", value: "number" },
          ],
          marks: {
            decorators: [
              { title: "Strong", value: "strong" },
              { title: "Emphasis", value: "em" },
              { title: "Code", value: "code" },
              { title: "Underline", value: "underline" },
            ],
            annotations: [
              {
                type: "object",
                name: "link",
                title: "url",
                fields: [
                  defineField({
                    type: "string",
                    name: "href",
                    title: "URL",
                    validation: (Rule) => Rule.required(),
                  }),
                  defineField({
                    type: "string",
                    name: "target",
                    title: "Target",
                    options: {
                      list: [
                        { value: "_blank", title: "Blank" },
                        { value: "_parent", title: "Parent" },
                      ],
                    },
                  }),
                ],
              },
            ],
          },
        },
        { type: "break" },
      ],
      title: "Content",
      hidden: false,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "displayStyle",
      type: "string",
      title: "Display Style",
      hidden: false,
      validation: (Rule) =>
        Rule.custom((value) =>
          validateIn(["caption", "paragraph", "list"], value),
        ),
      options: { list: ["caption", "paragraph", "list"] },
    }),
    defineField({
      type: "boolean",
      description:
        "If this document was archived on Contentful at the time of export, the document will be in a read-only state.",
      name: "contentfulArchived",
      readOnly: true,
    }),
  ],
  preview: { select: { title: "title" } },
  readOnly: ({ document }) =>
    (document == null ? void 0 : document.contentfulArchived) === !0,
});

export const breakType = defineType({
  name: "break",
  title: "Break",
  type: "object",
  fields: [
    defineField({
      name: "style",
      type: "string",
      options: {
        list: [
          { title: "Line break", value: "lineBreak" },
          { title: "Read more", value: "readMore" },
        ],
      },
    }),
  ],
});

export const types = [
  projectType,
  heroImagesType,
  aboutType,
  imageWithFocalPointType,
  assetsType,
  documentationType,
  imageWideType,
  containerVideoType,
  carouselType,
  blogPostType,
  baseContentType,
  textSectionType,
  contentSecionType,
  metadataSectionType,
  breakType,
] satisfies SchemaTypeDefinition[];
